// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkvPTNv_fd7eUedms0ThPD4zNa8hGQF4',
    appId: '1:298506194422:web:adf0869d26edc8f7c14bd7',
    messagingSenderId: '298506194422',
    projectId: 'viva-store-28598',
    authDomain: 'viva-store-28598.firebaseapp.com',
    storageBucket: 'viva-store-28598.appspot.com',
    measurementId: 'G-ZY5VX4YQL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvluH2Vzl2eRM9MfBST5rKLd-ESpi1wMs',
    appId: '1:298506194422:android:87415760f1f2b62fc14bd7',
    messagingSenderId: '298506194422',
    projectId: 'viva-store-28598',
    storageBucket: 'viva-store-28598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-TBH85jNOQh3vRcrbXdlhhuzJq5YBxoA',
    appId: '1:298506194422:ios:5ff6adaa6e65af84c14bd7',
    messagingSenderId: '298506194422',
    projectId: 'viva-store-28598',
    storageBucket: 'viva-store-28598.appspot.com',
    iosClientId: '298506194422-3ohjfoggs1fuskm7tt5jnscke939308s.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-TBH85jNOQh3vRcrbXdlhhuzJq5YBxoA',
    appId: '1:298506194422:ios:5ff6adaa6e65af84c14bd7',
    messagingSenderId: '298506194422',
    projectId: 'viva-store-28598',
    storageBucket: 'viva-store-28598.appspot.com',
    iosClientId: '298506194422-3ohjfoggs1fuskm7tt5jnscke939308s.apps.googleusercontent.com',
    iosBundleId: 'com.example.vivaStore',
  );
}
